// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/ang_store.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ANGStore_Set_FullMethodName                 = "/ang_store.ANGStore/Set"
	ANGStore_Get_FullMethodName                 = "/ang_store.ANGStore/Get"
	ANGStore_Delete_FullMethodName              = "/ang_store.ANGStore/Delete"
	ANGStore_Scan_FullMethodName                = "/ang_store.ANGStore/Scan"
	ANGStore_StoreMemory_FullMethodName         = "/ang_store.ANGStore/StoreMemory"
	ANGStore_GetMemory_FullMethodName           = "/ang_store.ANGStore/GetMemory"
	ANGStore_StoreTrainingSample_FullMethodName = "/ang_store.ANGStore/StoreTrainingSample"
	ANGStore_GetTrainingSamples_FullMethodName  = "/ang_store.ANGStore/GetTrainingSamples"
	ANGStore_Stats_FullMethodName               = "/ang_store.ANGStore/Stats"
)

// ANGStoreClient is the client API for ANGStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ANGStoreClient interface {
	// KV
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	// Memory / Conversations
	StoreMemory(ctx context.Context, in *StoreMemoryRequest, opts ...grpc.CallOption) (*StoreMemoryResponse, error)
	GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*GetMemoryResponse, error)
	// Training data
	StoreTrainingSample(ctx context.Context, in *StoreTrainingSampleRequest, opts ...grpc.CallOption) (*StoreTrainingSampleResponse, error)
	GetTrainingSamples(ctx context.Context, in *GetTrainingSamplesRequest, opts ...grpc.CallOption) (*GetTrainingSamplesResponse, error)
	// Stats
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type aNGStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewANGStoreClient(cc grpc.ClientConnInterface) ANGStoreClient {
	return &aNGStoreClient{cc}
}

func (c *aNGStoreClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, ANGStore_Set_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aNGStoreClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ANGStore_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aNGStoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ANGStore_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aNGStoreClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, ANGStore_Scan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aNGStoreClient) StoreMemory(ctx context.Context, in *StoreMemoryRequest, opts ...grpc.CallOption) (*StoreMemoryResponse, error) {
	out := new(StoreMemoryResponse)
	err := c.cc.Invoke(ctx, ANGStore_StoreMemory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aNGStoreClient) GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*GetMemoryResponse, error) {
	out := new(GetMemoryResponse)
	err := c.cc.Invoke(ctx, ANGStore_GetMemory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aNGStoreClient) StoreTrainingSample(ctx context.Context, in *StoreTrainingSampleRequest, opts ...grpc.CallOption) (*StoreTrainingSampleResponse, error) {
	out := new(StoreTrainingSampleResponse)
	err := c.cc.Invoke(ctx, ANGStore_StoreTrainingSample_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aNGStoreClient) GetTrainingSamples(ctx context.Context, in *GetTrainingSamplesRequest, opts ...grpc.CallOption) (*GetTrainingSamplesResponse, error) {
	out := new(GetTrainingSamplesResponse)
	err := c.cc.Invoke(ctx, ANGStore_GetTrainingSamples_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aNGStoreClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, ANGStore_Stats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ANGStoreServer is the server API for ANGStore service.
// All implementations must embed UnimplementedANGStoreServer
// for forward compatibility
type ANGStoreServer interface {
	// KV
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	// Memory / Conversations
	StoreMemory(context.Context, *StoreMemoryRequest) (*StoreMemoryResponse, error)
	GetMemory(context.Context, *GetMemoryRequest) (*GetMemoryResponse, error)
	// Training data
	StoreTrainingSample(context.Context, *StoreTrainingSampleRequest) (*StoreTrainingSampleResponse, error)
	GetTrainingSamples(context.Context, *GetTrainingSamplesRequest) (*GetTrainingSamplesResponse, error)
	// Stats
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedANGStoreServer()
}

// UnimplementedANGStoreServer must be embedded to have forward compatible implementations.
type UnimplementedANGStoreServer struct {
}

func (UnimplementedANGStoreServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedANGStoreServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedANGStoreServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedANGStoreServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedANGStoreServer) StoreMemory(context.Context, *StoreMemoryRequest) (*StoreMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreMemory not implemented")
}
func (UnimplementedANGStoreServer) GetMemory(context.Context, *GetMemoryRequest) (*GetMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemory not implemented")
}
func (UnimplementedANGStoreServer) StoreTrainingSample(context.Context, *StoreTrainingSampleRequest) (*StoreTrainingSampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreTrainingSample not implemented")
}
func (UnimplementedANGStoreServer) GetTrainingSamples(context.Context, *GetTrainingSamplesRequest) (*GetTrainingSamplesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrainingSamples not implemented")
}
func (UnimplementedANGStoreServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedANGStoreServer) mustEmbedUnimplementedANGStoreServer() {}

// UnsafeANGStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ANGStoreServer will
// result in compilation errors.
type UnsafeANGStoreServer interface {
	mustEmbedUnimplementedANGStoreServer()
}

func RegisterANGStoreServer(s grpc.ServiceRegistrar, srv ANGStoreServer) {
	s.RegisterService(&ANGStore_ServiceDesc, srv)
}

func _ANGStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ANGStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ANGStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ANGStore_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ANGStore_StoreMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).StoreMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_StoreMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).StoreMemory(ctx, req.(*StoreMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ANGStore_GetMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).GetMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_GetMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).GetMemory(ctx, req.(*GetMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ANGStore_StoreTrainingSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTrainingSampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).StoreTrainingSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_StoreTrainingSample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).StoreTrainingSample(ctx, req.(*StoreTrainingSampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ANGStore_GetTrainingSamples_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainingSamplesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).GetTrainingSamples(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_GetTrainingSamples_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).GetTrainingSamples(ctx, req.(*GetTrainingSamplesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ANGStore_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ANGStoreServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ANGStore_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ANGStoreServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ANGStore_ServiceDesc is the grpc.ServiceDesc for ANGStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ANGStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ang_store.ANGStore",
	HandlerType: (*ANGStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _ANGStore_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ANGStore_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ANGStore_Delete_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _ANGStore_Scan_Handler,
		},
		{
			MethodName: "StoreMemory",
			Handler:    _ANGStore_StoreMemory_Handler,
		},
		{
			MethodName: "GetMemory",
			Handler:    _ANGStore_GetMemory_Handler,
		},
		{
			MethodName: "StoreTrainingSample",
			Handler:    _ANGStore_StoreTrainingSample_Handler,
		},
		{
			MethodName: "GetTrainingSamples",
			Handler:    _ANGStore_GetTrainingSamples_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _ANGStore_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ang_store.proto",
}
