# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import ang_store_pb2 as proto_dot_ang__store__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/ang_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ANGStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Set = channel.unary_unary(
                '/ang_store.ANGStore/Set',
                request_serializer=proto_dot_ang__store__pb2.SetRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.SetResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/ang_store.ANGStore/Get',
                request_serializer=proto_dot_ang__store__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/ang_store.ANGStore/Delete',
                request_serializer=proto_dot_ang__store__pb2.DeleteRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_unary(
                '/ang_store.ANGStore/Scan',
                request_serializer=proto_dot_ang__store__pb2.ScanRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.StoreMemory = channel.unary_unary(
                '/ang_store.ANGStore/StoreMemory',
                request_serializer=proto_dot_ang__store__pb2.StoreMemoryRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.StoreMemoryResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/ang_store.ANGStore/GetMemory',
                request_serializer=proto_dot_ang__store__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.GetMemoryResponse.FromString,
                _registered_method=True)
        self.StoreTrainingSample = channel.unary_unary(
                '/ang_store.ANGStore/StoreTrainingSample',
                request_serializer=proto_dot_ang__store__pb2.StoreTrainingSampleRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.StoreTrainingSampleResponse.FromString,
                _registered_method=True)
        self.GetTrainingSamples = channel.unary_unary(
                '/ang_store.ANGStore/GetTrainingSamples',
                request_serializer=proto_dot_ang__store__pb2.GetTrainingSamplesRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.GetTrainingSamplesResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/ang_store.ANGStore/Stats',
                request_serializer=proto_dot_ang__store__pb2.StatsRequest.SerializeToString,
                response_deserializer=proto_dot_ang__store__pb2.StatsResponse.FromString,
                _registered_method=True)


class ANGStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Set(self, request, context):
        """KV
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreMemory(self, request, context):
        """Memory / Conversations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreTrainingSample(self, request, context):
        """Training data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingSamples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ANGStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=proto_dot_ang__store__pb2.SetRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.SetResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=proto_dot_ang__store__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=proto_dot_ang__store__pb2.DeleteRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.DeleteResponse.SerializeToString,
            ),
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=proto_dot_ang__store__pb2.ScanRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.ScanResponse.SerializeToString,
            ),
            'StoreMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMemory,
                    request_deserializer=proto_dot_ang__store__pb2.StoreMemoryRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.StoreMemoryResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=proto_dot_ang__store__pb2.GetMemoryRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.GetMemoryResponse.SerializeToString,
            ),
            'StoreTrainingSample': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreTrainingSample,
                    request_deserializer=proto_dot_ang__store__pb2.StoreTrainingSampleRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.StoreTrainingSampleResponse.SerializeToString,
            ),
            'GetTrainingSamples': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingSamples,
                    request_deserializer=proto_dot_ang__store__pb2.GetTrainingSamplesRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.GetTrainingSamplesResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=proto_dot_ang__store__pb2.StatsRequest.FromString,
                    response_serializer=proto_dot_ang__store__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ang_store.ANGStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ang_store.ANGStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ANGStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/Set',
            proto_dot_ang__store__pb2.SetRequest.SerializeToString,
            proto_dot_ang__store__pb2.SetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/Get',
            proto_dot_ang__store__pb2.GetRequest.SerializeToString,
            proto_dot_ang__store__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/Delete',
            proto_dot_ang__store__pb2.DeleteRequest.SerializeToString,
            proto_dot_ang__store__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/Scan',
            proto_dot_ang__store__pb2.ScanRequest.SerializeToString,
            proto_dot_ang__store__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/StoreMemory',
            proto_dot_ang__store__pb2.StoreMemoryRequest.SerializeToString,
            proto_dot_ang__store__pb2.StoreMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/GetMemory',
            proto_dot_ang__store__pb2.GetMemoryRequest.SerializeToString,
            proto_dot_ang__store__pb2.GetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreTrainingSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/StoreTrainingSample',
            proto_dot_ang__store__pb2.StoreTrainingSampleRequest.SerializeToString,
            proto_dot_ang__store__pb2.StoreTrainingSampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingSamples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/GetTrainingSamples',
            proto_dot_ang__store__pb2.GetTrainingSamplesRequest.SerializeToString,
            proto_dot_ang__store__pb2.GetTrainingSamplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ang_store.ANGStore/Stats',
            proto_dot_ang__store__pb2.StatsRequest.SerializeToString,
            proto_dot_ang__store__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
